# Generated by Django 4.0.2 on 2022-02-19 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_number', models.CharField(max_length=8, unique=True)),
                ('tex_passport_number', models.CharField(max_length=10, unique=True)),
                ('type_of_car', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Litsence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('given_date', models.DateField()),
                ('deadline_date', models.DateField()),
                ('car_state_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blok.cars')),
            ],
        ),
        migrations.AddField(
            model_name='drivers',
            name='address',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivers',
            name='phone_number',
            field=models.CharField(default=12, max_length=9),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Putyovka',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('money', models.FloatField()),
                ('state_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blok.litsence')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blok.drivers'),
        ),
    ]
