# Generated by Django 4.0.2 on 2022-02-20 04:06

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0003_alter_cars_options_alter_drivers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
