# Generated by Django 4.0.2 on 2022-02-20 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0004_alter_drivers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putyovka',
            name='state_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blok.cars'),
        ),
    ]
