# Generated by Django 4.0.2 on 2022-02-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0005_alter_putyovka_state_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='putyovka',
            name='money',
            field=models.IntegerField(),
        ),
    ]
