# Generated by Django 4.0.2 on 2022-02-20 04:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0006_alter_putyovka_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blok.drivers', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='address',
            field=models.TextField(verbose_name='Aдрес'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='passport_image',
            field=models.ImageField(upload_to='images', verbose_name='Kопия паспорта'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Tелефонный номер'),
        ),
    ]
