# Generated by Django 4.0.2 on 2022-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0008_litsence_comments_putyovka_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Ид'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivers',
            name='number',
            field=models.IntegerField(default=2, unique=True, verbose_name='Ид'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='litsence',
            name='number',
            field=models.IntegerField(default=3, unique=True, verbose_name='Ид'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='litsence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='putyovka',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
