# Generated by Django 4.0.2 on 2022-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0009_cars_number_drivers_number_litsence_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drivers',
            options={'ordering': ('number',), 'verbose_name': 'Bодители', 'verbose_name_plural': 'Bодители'},
        ),
        migrations.AlterField(
            model_name='drivers',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Kопия паспорта'),
        ),
    ]
