# Generated by Django 4.0.2 on 2022-02-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0011_alter_cars_options_alter_litsence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='Tелефонный номер'),
        ),
    ]
